import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { literal, relativePath } from "./helpers.ts";
import type { ProjectContext } from "../../core/types.ts";
import type { ResolvedConfig } from "../../core/schema.ts";

export const astroConfigTemplate = ({
  context,
  config,
  dataPath,
}: {
  context: ProjectContext;
  config: ResolvedConfig;
  dataPath: string;
}): string => {
  // Astro's native i18n gives locale-aware helpers + `<html lang>` correctness.
  // Brandtree owns getStaticPaths and materializes fallback routes in the manifest,
  // so we deliberately omit Astro's `fallback` to keep one source of routing.
  const i18n = config.i18n
    ? `${literal({
        defaultLocale: config.i18n.defaultLocale,
        locales: config.i18n.locales.map((locale) => locale.code),
        routing: "manual",
      })}`
    : undefined;

  const mdxImport = `import mdx from "@astrojs/mdx";\n`;
  const reactImport = `import react from "@astrojs/react";\n`;
  const tailwindImport = `import tailwindcss from "@tailwindcss/vite";\n`;

  const integrations = [`mdx()`, `react()`];

  const fonts = config.fonts.map((font) => {
    if (font.provider === "adobe") {
      const { provider, id, ...family } = font;
      return `{ ...${literal(family)}, provider: fontProviders.adobe(${literal({ id })}) }`;
    }
    if (font.provider !== "local") {
      const { provider, ...family } = font;
      return `{ ...${literal(family)}, provider: fontProviders.${provider}() }`;
    }
    const { provider, options, ...family } = font;
    const variants = options.variants.map(({ src, ...variant }) => {
      const sources = src.map((source) => {
        const url = /^[a-z][a-z0-9+.-]*:/iu.test(source)
          ? source
          : pathToFileURL(resolve(context.root, source)).href;
        return `new URL(${literal(url)})`;
      });
      return `{ ...${literal(variant)}, src: [${sources.join(", ")}] }`;
    });
    return `{ ...${literal(family)}, provider: fontProviders.local(), options: { variants: [${variants.join(", ")}] } }`;
  });

  return String.raw`// Generated by Brandtree. Do not edit; this file is recreated on each run.
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { prerenderDeps } from 'brandtree/astro/prerender-deps';

// Resolve framework-owned dependencies from the installed Brandtree package.
const frameworkEntry = import.meta.resolve('brandtree');
const frameworkRequire = createRequire(frameworkEntry);

const [{ defineConfig, fontProviders }, { default: mdx }, { default: react }, { default: tailwindcss }] =
  await Promise.all(['astro/config', '@astrojs/mdx', '@astrojs/react', '@tailwindcss/vite'].map(
    (specifier) => import(frameworkRequire.resolve(specifier)),
  ));

export default defineConfig({
  publicDir: fileURLToPath(new URL(${literal(relativePath(context.outDir, join(context.root, "public")) + "/")}, import.meta.url)),
  outDir: fileURLToPath(new URL(${literal(relativePath(context.outDir, context.distDir ?? join(context.root, "dist")) + "/")}, import.meta.url)),
  site: ${literal(config.brand.meta.url)},
  output: 'static',
  fonts: [${fonts.join(",\n")}],
  integrations: [${integrations.join(", ")}],
  i18n: ${i18n},
  vite: {
    plugins: [tailwindcss(), prerenderDeps()],
    resolve: {
      alias: {
        "brandtree:data": ${literal(dataPath)},
      },
    },
  },
})`;
};
