import { join } from "node:path";
import { literal, relativePath } from "./helpers.ts";
import type { ProjectContext } from "../../core/types.ts";
import type { ResolvedConfig } from "../../core/schema.ts";

export const astroConfigTemplate = ({
  context,
  config,
  dataPath,
}: {
  context: ProjectContext;
  config: ResolvedConfig;
  dataPath: string;
}): string => {
  // Brandtree generates locale paths, redirects, and fallback pages itself.
  // Retain Astro's locale helpers without its automatic routing enforcement.
  const i18n = config.i18n
    ? `i18n: ${JSON.stringify({
        defaultLocale: config.i18n.defaultLocale,
        locales: config.i18n.locales.map((locale) => locale.code),
        routing: "manual",
      })}`
    : "";

  const mdxImport = `import mdx from "@astrojs/mdx";\n`;
  const reactImport = `import react from "@astrojs/react";\n`;
  const tailwindImport = `import tailwindcss from "@tailwindcss/vite";\n`;

  const integrations = [`mdx()`, `react()`];

  return String.raw`// Generated by Brandtree. Do not edit; this file is recreated on each run.
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { prerenderDeps } from 'brandtree/astro/prerender-deps';

// Resolve framework-owned dependencies from the installed Brandtree package.
const frameworkEntry = import.meta.resolve('brandtree');
const frameworkRequire = createRequire(frameworkEntry);

const [{ defineConfig }, { default: mdx }, { default: react }, { default: tailwindcss }] =
  await Promise.all(['astro/config', '@astrojs/mdx', '@astrojs/react', '@tailwindcss/vite'].map(
    (specifier) => import(frameworkRequire.resolve(specifier)),
  ));

export default defineConfig({
  publicDir: fileURLToPath(new URL(${literal(relativePath(context.outDir, join(context.root, "public")) + "/")}, import.meta.url)),
  outDir: fileURLToPath(new URL(${literal(relativePath(context.outDir, context.distDir ?? join(context.root, "dist")) + "/")}, import.meta.url)),
  site: ${literal(config.brand.meta.url)},
  output: 'static',${i18nOption}
  integrations: [${integrations.join(", ")}],
  i18n: ${i18n},
  vite: {
    plugins: [tailwindcss(), prerenderDeps()],
    resolve: {
      alias: {
        "brandtree:data": ${literal(dataPath)},
      },
    },
  },
})`;
};
