import type { ResolvedConfig } from "../../core/schema.ts";
import type { ProjectContext } from "../../core/types.ts";
import { literal, relativePath } from "./helpers.ts";

export const contentConfigTemplate = (options: {
  context: ProjectContext;
  config: ResolvedConfig;
}): string => {
  const { context, config } = options;

  return `// Generated by Brandtree. Do not edit.
import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { pageMetaSchema } from 'brandtree';

export const collections = {
  docs: defineCollection({
    loader: glob({
      base: ${literal(relativePath(context.outDir, context.contentRoot))},
      pattern: ['**/*.{md,mdx}', '!**/_*', '!**/_*/**', '!**/{node_modules,dist,coverage,.git,.astro,.brandtree}/**'],
      generateId: ({ entry }) => entry.replaceAll('\\\\', '/'),
    }),
    schema: pageMetaSchema,
  }),
};
`;
};
