/** Compatibility-facing exports for the schema-backed brand configuration. */
export {
  brandColorValueSchema,
  brandColorsSchema,
  brandConfigSchema,
  defineBrand,
  i18nConfigSchema,
  navigationConfigSchema,
  shadeSteps,
} from "./schema";

export type {
  BrandColorFamily,
  BrandColorReference,
  BrandColorToken,
  BrandColorValue,
  BrandColors,
  BrandConfig,
  BrandConfigInput,
  BrandContact,
  BrandDownload,
  BrandLocaleOverride,
  BrandLocaleOverrides,
  BrandLogo,
  BrandMeta,
  BrandScheme,
  BrandShadeStep,
  BrandSpecialColor,
  BrandSwatch,
  BrandTheme,
  BrandTypography,
  FontWeightSpec,
  I18nConfig,
  I18nConfigInput,
  LogoArtwork,
  NavigationConfig,
  NavigationConfigInput,
  TypeStyle,
} from "./schema";
